import { Project } from './project-data.ts';

export const PROJECTS: Project[] = [
  {id: 1, name: "An ecommerce front end landing page",
skills: "HTML, JavaScript, Sass, jQuery",
description: "This is a landing page I made for a client in the UK(rufflefordogs.com)",
url:"rufflefordogs.herokuapp.com"},
{id:2,
name:"A blog made with React and Redux",
skills:"React, Redux, Express, MongoDB, Passport authentication, Radium CSS, Node.js",
description:"This is a MERN stack blog that contains features such as creating, updating, deleting, and reading posts. It also has an authentication system.",
url:"reactreduxblogcc.herokuapp.com"},
{id:4,
name:"An English Name Generator",
skills:"React, Express, CSS, Node.js",
description:"This is a MERN stack blog that contains features such as creating, updating, deleting, and reading posts. It also has an authentication system.",
url:"reactreduxblogcc.herokuapp.com"},
{id:2,
name:"A blog made with React and Redux",
skills:"React, Redux, Express, MongoDB, Passport authentication, Radium CSS, Node.js",
description:"This is a MERN stack blog that contains features such as creating, updating, deleting, and reading posts. It also has an authentication system.",
url:"reactreduxblogcc.herokuapp.com"},
{id:2,
name:"A blog made with React and Redux",
skills:"React, Redux, Express, MongoDB, Passport authentication, Radium CSS, Node.js",
description:"This is a MERN stack blog that contains features such as creating, updating, deleting, and reading posts. It also has an authentication system.",
url:"reactreduxblogcc.herokuapp.com"},
]
